/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiChannelRouteImport } from './routes/api/channel'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiDeleteModelRouteImport } from './routes/api/delete-model'
import { Route as ApiGithubAuthRouteImport } from './routes/api/github-auth'
import { Route as ApiGithubCloneRouteImport } from './routes/api/github-clone'
import { Route as ApiGithubPrRouteImport } from './routes/api/github-pr'
import { Route as ApiGithubPullRouteImport } from './routes/api/github-pull'
import { Route as ApiLibraryRouteImport } from './routes/api/library'
import { Route as ApiMcpRouteImport } from './routes/api/mcp'
import { Route as ApiModelsRouteImport } from './routes/api/models'
import { Route as ApiN8nRouteImport } from './routes/api/n8n'
import { Route as ApiNewsRouteImport } from './routes/api/news'
import { Route as ApiOauthRouteImport } from './routes/api/oauth'
import { Route as ApiPullRouteImport } from './routes/api/pull'
import { Route as ApiResetRouteImport } from './routes/api/reset'
import { Route as ApiSetupRouteImport } from './routes/api/setup'
import { Route as ApiSetupInstallRouteImport } from './routes/api/setup-install'
import { Route as ApiSetupStartRouteImport } from './routes/api/setup-start'
import { Route as ApiStudioRouteImport } from './routes/api/studio'
import { Route as ApiTokenizeRouteImport } from './routes/api/tokenize'
import { Route as ApiN8nDispatchRouteImport } from './routes/api/n8n.dispatch'
import { Route as ApiN8nLaneRouteImport } from './routes/api/n8n.lane'
import { Route as ApiN8nTestRouteImport } from './routes/api/n8n.test'
import { Route as ApiN8nWorkflowsRouteImport } from './routes/api/n8n.workflows'
import { Route as ApiV1ModelsRouteImport } from './routes/api/v1.models'
import { Route as ApiV1ChatCompletionsRouteImport } from './routes/api/v1.chat.completions'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChannelRoute = ApiChannelRouteImport.update({
  id: '/api/channel',
  path: '/api/channel',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDeleteModelRoute = ApiDeleteModelRouteImport.update({
  id: '/api/delete-model',
  path: '/api/delete-model',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGithubAuthRoute = ApiGithubAuthRouteImport.update({
  id: '/api/github-auth',
  path: '/api/github-auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGithubCloneRoute = ApiGithubCloneRouteImport.update({
  id: '/api/github-clone',
  path: '/api/github-clone',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGithubPrRoute = ApiGithubPrRouteImport.update({
  id: '/api/github-pr',
  path: '/api/github-pr',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGithubPullRoute = ApiGithubPullRouteImport.update({
  id: '/api/github-pull',
  path: '/api/github-pull',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLibraryRoute = ApiLibraryRouteImport.update({
  id: '/api/library',
  path: '/api/library',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMcpRoute = ApiMcpRouteImport.update({
  id: '/api/mcp',
  path: '/api/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiModelsRoute = ApiModelsRouteImport.update({
  id: '/api/models',
  path: '/api/models',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiN8nRoute = ApiN8nRouteImport.update({
  id: '/api/n8n',
  path: '/api/n8n',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNewsRoute = ApiNewsRouteImport.update({
  id: '/api/news',
  path: '/api/news',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOauthRoute = ApiOauthRouteImport.update({
  id: '/api/oauth',
  path: '/api/oauth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPullRoute = ApiPullRouteImport.update({
  id: '/api/pull',
  path: '/api/pull',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiResetRoute = ApiResetRouteImport.update({
  id: '/api/reset',
  path: '/api/reset',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSetupRoute = ApiSetupRouteImport.update({
  id: '/api/setup',
  path: '/api/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSetupInstallRoute = ApiSetupInstallRouteImport.update({
  id: '/api/setup-install',
  path: '/api/setup-install',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSetupStartRoute = ApiSetupStartRouteImport.update({
  id: '/api/setup-start',
  path: '/api/setup-start',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStudioRoute = ApiStudioRouteImport.update({
  id: '/api/studio',
  path: '/api/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTokenizeRoute = ApiTokenizeRouteImport.update({
  id: '/api/tokenize',
  path: '/api/tokenize',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiN8nDispatchRoute = ApiN8nDispatchRouteImport.update({
  id: '/dispatch',
  path: '/dispatch',
  getParentRoute: () => ApiN8nRoute,
} as any)
const ApiN8nLaneRoute = ApiN8nLaneRouteImport.update({
  id: '/lane',
  path: '/lane',
  getParentRoute: () => ApiN8nRoute,
} as any)
const ApiN8nTestRoute = ApiN8nTestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => ApiN8nRoute,
} as any)
const ApiN8nWorkflowsRoute = ApiN8nWorkflowsRouteImport.update({
  id: '/workflows',
  path: '/workflows',
  getParentRoute: () => ApiN8nRoute,
} as any)
const ApiV1ModelsRoute = ApiV1ModelsRouteImport.update({
  id: '/api/v1/models',
  path: '/api/v1/models',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1ChatCompletionsRoute = ApiV1ChatCompletionsRouteImport.update({
  id: '/api/v1/chat/completions',
  path: '/api/v1/chat/completions',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/channel': typeof ApiChannelRoute
  '/api/chat': typeof ApiChatRoute
  '/api/delete-model': typeof ApiDeleteModelRoute
  '/api/github-auth': typeof ApiGithubAuthRoute
  '/api/github-clone': typeof ApiGithubCloneRoute
  '/api/github-pr': typeof ApiGithubPrRoute
  '/api/github-pull': typeof ApiGithubPullRoute
  '/api/library': typeof ApiLibraryRoute
  '/api/mcp': typeof ApiMcpRoute
  '/api/models': typeof ApiModelsRoute
  '/api/n8n': typeof ApiN8nRouteWithChildren
  '/api/news': typeof ApiNewsRoute
  '/api/oauth': typeof ApiOauthRoute
  '/api/pull': typeof ApiPullRoute
  '/api/reset': typeof ApiResetRoute
  '/api/setup': typeof ApiSetupRoute
  '/api/setup-install': typeof ApiSetupInstallRoute
  '/api/setup-start': typeof ApiSetupStartRoute
  '/api/studio': typeof ApiStudioRoute
  '/api/tokenize': typeof ApiTokenizeRoute
  '/api/n8n/dispatch': typeof ApiN8nDispatchRoute
  '/api/n8n/lane': typeof ApiN8nLaneRoute
  '/api/n8n/test': typeof ApiN8nTestRoute
  '/api/n8n/workflows': typeof ApiN8nWorkflowsRoute
  '/api/v1/models': typeof ApiV1ModelsRoute
  '/api/v1/chat/completions': typeof ApiV1ChatCompletionsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/channel': typeof ApiChannelRoute
  '/api/chat': typeof ApiChatRoute
  '/api/delete-model': typeof ApiDeleteModelRoute
  '/api/github-auth': typeof ApiGithubAuthRoute
  '/api/github-clone': typeof ApiGithubCloneRoute
  '/api/github-pr': typeof ApiGithubPrRoute
  '/api/github-pull': typeof ApiGithubPullRoute
  '/api/library': typeof ApiLibraryRoute
  '/api/mcp': typeof ApiMcpRoute
  '/api/models': typeof ApiModelsRoute
  '/api/n8n': typeof ApiN8nRouteWithChildren
  '/api/news': typeof ApiNewsRoute
  '/api/oauth': typeof ApiOauthRoute
  '/api/pull': typeof ApiPullRoute
  '/api/reset': typeof ApiResetRoute
  '/api/setup': typeof ApiSetupRoute
  '/api/setup-install': typeof ApiSetupInstallRoute
  '/api/setup-start': typeof ApiSetupStartRoute
  '/api/studio': typeof ApiStudioRoute
  '/api/tokenize': typeof ApiTokenizeRoute
  '/api/n8n/dispatch': typeof ApiN8nDispatchRoute
  '/api/n8n/lane': typeof ApiN8nLaneRoute
  '/api/n8n/test': typeof ApiN8nTestRoute
  '/api/n8n/workflows': typeof ApiN8nWorkflowsRoute
  '/api/v1/models': typeof ApiV1ModelsRoute
  '/api/v1/chat/completions': typeof ApiV1ChatCompletionsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/channel': typeof ApiChannelRoute
  '/api/chat': typeof ApiChatRoute
  '/api/delete-model': typeof ApiDeleteModelRoute
  '/api/github-auth': typeof ApiGithubAuthRoute
  '/api/github-clone': typeof ApiGithubCloneRoute
  '/api/github-pr': typeof ApiGithubPrRoute
  '/api/github-pull': typeof ApiGithubPullRoute
  '/api/library': typeof ApiLibraryRoute
  '/api/mcp': typeof ApiMcpRoute
  '/api/models': typeof ApiModelsRoute
  '/api/n8n': typeof ApiN8nRouteWithChildren
  '/api/news': typeof ApiNewsRoute
  '/api/oauth': typeof ApiOauthRoute
  '/api/pull': typeof ApiPullRoute
  '/api/reset': typeof ApiResetRoute
  '/api/setup': typeof ApiSetupRoute
  '/api/setup-install': typeof ApiSetupInstallRoute
  '/api/setup-start': typeof ApiSetupStartRoute
  '/api/studio': typeof ApiStudioRoute
  '/api/tokenize': typeof ApiTokenizeRoute
  '/api/n8n/dispatch': typeof ApiN8nDispatchRoute
  '/api/n8n/lane': typeof ApiN8nLaneRoute
  '/api/n8n/test': typeof ApiN8nTestRoute
  '/api/n8n/workflows': typeof ApiN8nWorkflowsRoute
  '/api/v1/models': typeof ApiV1ModelsRoute
  '/api/v1/chat/completions': typeof ApiV1ChatCompletionsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/channel'
    | '/api/chat'
    | '/api/delete-model'
    | '/api/github-auth'
    | '/api/github-clone'
    | '/api/github-pr'
    | '/api/github-pull'
    | '/api/library'
    | '/api/mcp'
    | '/api/models'
    | '/api/n8n'
    | '/api/news'
    | '/api/oauth'
    | '/api/pull'
    | '/api/reset'
    | '/api/setup'
    | '/api/setup-install'
    | '/api/setup-start'
    | '/api/studio'
    | '/api/tokenize'
    | '/api/n8n/dispatch'
    | '/api/n8n/lane'
    | '/api/n8n/test'
    | '/api/n8n/workflows'
    | '/api/v1/models'
    | '/api/v1/chat/completions'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/channel'
    | '/api/chat'
    | '/api/delete-model'
    | '/api/github-auth'
    | '/api/github-clone'
    | '/api/github-pr'
    | '/api/github-pull'
    | '/api/library'
    | '/api/mcp'
    | '/api/models'
    | '/api/n8n'
    | '/api/news'
    | '/api/oauth'
    | '/api/pull'
    | '/api/reset'
    | '/api/setup'
    | '/api/setup-install'
    | '/api/setup-start'
    | '/api/studio'
    | '/api/tokenize'
    | '/api/n8n/dispatch'
    | '/api/n8n/lane'
    | '/api/n8n/test'
    | '/api/n8n/workflows'
    | '/api/v1/models'
    | '/api/v1/chat/completions'
  id:
    | '__root__'
    | '/'
    | '/api/channel'
    | '/api/chat'
    | '/api/delete-model'
    | '/api/github-auth'
    | '/api/github-clone'
    | '/api/github-pr'
    | '/api/github-pull'
    | '/api/library'
    | '/api/mcp'
    | '/api/models'
    | '/api/n8n'
    | '/api/news'
    | '/api/oauth'
    | '/api/pull'
    | '/api/reset'
    | '/api/setup'
    | '/api/setup-install'
    | '/api/setup-start'
    | '/api/studio'
    | '/api/tokenize'
    | '/api/n8n/dispatch'
    | '/api/n8n/lane'
    | '/api/n8n/test'
    | '/api/n8n/workflows'
    | '/api/v1/models'
    | '/api/v1/chat/completions'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiChannelRoute: typeof ApiChannelRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiDeleteModelRoute: typeof ApiDeleteModelRoute
  ApiGithubAuthRoute: typeof ApiGithubAuthRoute
  ApiGithubCloneRoute: typeof ApiGithubCloneRoute
  ApiGithubPrRoute: typeof ApiGithubPrRoute
  ApiGithubPullRoute: typeof ApiGithubPullRoute
  ApiLibraryRoute: typeof ApiLibraryRoute
  ApiMcpRoute: typeof ApiMcpRoute
  ApiModelsRoute: typeof ApiModelsRoute
  ApiN8nRoute: typeof ApiN8nRouteWithChildren
  ApiNewsRoute: typeof ApiNewsRoute
  ApiOauthRoute: typeof ApiOauthRoute
  ApiPullRoute: typeof ApiPullRoute
  ApiResetRoute: typeof ApiResetRoute
  ApiSetupRoute: typeof ApiSetupRoute
  ApiSetupInstallRoute: typeof ApiSetupInstallRoute
  ApiSetupStartRoute: typeof ApiSetupStartRoute
  ApiStudioRoute: typeof ApiStudioRoute
  ApiTokenizeRoute: typeof ApiTokenizeRoute
  ApiV1ModelsRoute: typeof ApiV1ModelsRoute
  ApiV1ChatCompletionsRoute: typeof ApiV1ChatCompletionsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/channel': {
      id: '/api/channel'
      path: '/api/channel'
      fullPath: '/api/channel'
      preLoaderRoute: typeof ApiChannelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/delete-model': {
      id: '/api/delete-model'
      path: '/api/delete-model'
      fullPath: '/api/delete-model'
      preLoaderRoute: typeof ApiDeleteModelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/github-auth': {
      id: '/api/github-auth'
      path: '/api/github-auth'
      fullPath: '/api/github-auth'
      preLoaderRoute: typeof ApiGithubAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/github-clone': {
      id: '/api/github-clone'
      path: '/api/github-clone'
      fullPath: '/api/github-clone'
      preLoaderRoute: typeof ApiGithubCloneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/github-pr': {
      id: '/api/github-pr'
      path: '/api/github-pr'
      fullPath: '/api/github-pr'
      preLoaderRoute: typeof ApiGithubPrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/github-pull': {
      id: '/api/github-pull'
      path: '/api/github-pull'
      fullPath: '/api/github-pull'
      preLoaderRoute: typeof ApiGithubPullRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/library': {
      id: '/api/library'
      path: '/api/library'
      fullPath: '/api/library'
      preLoaderRoute: typeof ApiLibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mcp': {
      id: '/api/mcp'
      path: '/api/mcp'
      fullPath: '/api/mcp'
      preLoaderRoute: typeof ApiMcpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/models': {
      id: '/api/models'
      path: '/api/models'
      fullPath: '/api/models'
      preLoaderRoute: typeof ApiModelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/n8n': {
      id: '/api/n8n'
      path: '/api/n8n'
      fullPath: '/api/n8n'
      preLoaderRoute: typeof ApiN8nRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/news': {
      id: '/api/news'
      path: '/api/news'
      fullPath: '/api/news'
      preLoaderRoute: typeof ApiNewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/oauth': {
      id: '/api/oauth'
      path: '/api/oauth'
      fullPath: '/api/oauth'
      preLoaderRoute: typeof ApiOauthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pull': {
      id: '/api/pull'
      path: '/api/pull'
      fullPath: '/api/pull'
      preLoaderRoute: typeof ApiPullRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/reset': {
      id: '/api/reset'
      path: '/api/reset'
      fullPath: '/api/reset'
      preLoaderRoute: typeof ApiResetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/setup': {
      id: '/api/setup'
      path: '/api/setup'
      fullPath: '/api/setup'
      preLoaderRoute: typeof ApiSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/setup-install': {
      id: '/api/setup-install'
      path: '/api/setup-install'
      fullPath: '/api/setup-install'
      preLoaderRoute: typeof ApiSetupInstallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/setup-start': {
      id: '/api/setup-start'
      path: '/api/setup-start'
      fullPath: '/api/setup-start'
      preLoaderRoute: typeof ApiSetupStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/studio': {
      id: '/api/studio'
      path: '/api/studio'
      fullPath: '/api/studio'
      preLoaderRoute: typeof ApiStudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tokenize': {
      id: '/api/tokenize'
      path: '/api/tokenize'
      fullPath: '/api/tokenize'
      preLoaderRoute: typeof ApiTokenizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/n8n/dispatch': {
      id: '/api/n8n/dispatch'
      path: '/dispatch'
      fullPath: '/api/n8n/dispatch'
      preLoaderRoute: typeof ApiN8nDispatchRouteImport
      parentRoute: typeof ApiN8nRoute
    }
    '/api/n8n/lane': {
      id: '/api/n8n/lane'
      path: '/lane'
      fullPath: '/api/n8n/lane'
      preLoaderRoute: typeof ApiN8nLaneRouteImport
      parentRoute: typeof ApiN8nRoute
    }
    '/api/n8n/test': {
      id: '/api/n8n/test'
      path: '/test'
      fullPath: '/api/n8n/test'
      preLoaderRoute: typeof ApiN8nTestRouteImport
      parentRoute: typeof ApiN8nRoute
    }
    '/api/n8n/workflows': {
      id: '/api/n8n/workflows'
      path: '/workflows'
      fullPath: '/api/n8n/workflows'
      preLoaderRoute: typeof ApiN8nWorkflowsRouteImport
      parentRoute: typeof ApiN8nRoute
    }
    '/api/v1/models': {
      id: '/api/v1/models'
      path: '/api/v1/models'
      fullPath: '/api/v1/models'
      preLoaderRoute: typeof ApiV1ModelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/chat/completions': {
      id: '/api/v1/chat/completions'
      path: '/api/v1/chat/completions'
      fullPath: '/api/v1/chat/completions'
      preLoaderRoute: typeof ApiV1ChatCompletionsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ApiN8nRouteChildren {
  ApiN8nDispatchRoute: typeof ApiN8nDispatchRoute
  ApiN8nLaneRoute: typeof ApiN8nLaneRoute
  ApiN8nTestRoute: typeof ApiN8nTestRoute
  ApiN8nWorkflowsRoute: typeof ApiN8nWorkflowsRoute
}

const ApiN8nRouteChildren: ApiN8nRouteChildren = {
  ApiN8nDispatchRoute: ApiN8nDispatchRoute,
  ApiN8nLaneRoute: ApiN8nLaneRoute,
  ApiN8nTestRoute: ApiN8nTestRoute,
  ApiN8nWorkflowsRoute: ApiN8nWorkflowsRoute,
}

const ApiN8nRouteWithChildren =
  ApiN8nRoute._addFileChildren(ApiN8nRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiChannelRoute: ApiChannelRoute,
  ApiChatRoute: ApiChatRoute,
  ApiDeleteModelRoute: ApiDeleteModelRoute,
  ApiGithubAuthRoute: ApiGithubAuthRoute,
  ApiGithubCloneRoute: ApiGithubCloneRoute,
  ApiGithubPrRoute: ApiGithubPrRoute,
  ApiGithubPullRoute: ApiGithubPullRoute,
  ApiLibraryRoute: ApiLibraryRoute,
  ApiMcpRoute: ApiMcpRoute,
  ApiModelsRoute: ApiModelsRoute,
  ApiN8nRoute: ApiN8nRouteWithChildren,
  ApiNewsRoute: ApiNewsRoute,
  ApiOauthRoute: ApiOauthRoute,
  ApiPullRoute: ApiPullRoute,
  ApiResetRoute: ApiResetRoute,
  ApiSetupRoute: ApiSetupRoute,
  ApiSetupInstallRoute: ApiSetupInstallRoute,
  ApiSetupStartRoute: ApiSetupStartRoute,
  ApiStudioRoute: ApiStudioRoute,
  ApiTokenizeRoute: ApiTokenizeRoute,
  ApiV1ModelsRoute: ApiV1ModelsRoute,
  ApiV1ChatCompletionsRoute: ApiV1ChatCompletionsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
